name: Cross-Platform Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up LLVM 18 on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-18 llvm-18-dev clang-18 lld-18
          echo "/usr/lib/llvm-18/bin" >> $GITHUB_PATH

      - name: Set up LLVM 18 on Windows
        if: runner.os == 'Windows'
        run: |
          choco install llvm --version 18.0.0 -y
          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set up LLVM 18 on macOS
        if: runner.os == 'macOS'
        run: |
          brew install llvm@18
          echo "/usr/local/opt/llvm@18/bin" >> $GITHUB_PATH

      - name: Build on Linux and Mac
        if: runner.os != 'Windows'
        run: |
          chmod +x build.sh
          bash build.sh  # 直接使用 bash 命令运行

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: |
          choco install git -y
          C:\ProgramData\chocolatey\lib\git\tools\git-bash.exe -c "bash build.sh"

      - name: Package artifacts
        run: |
          mkdir artifacts
          cp -r bin lib artifacts
          tar -czvf artifacts.tar.gz artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: artifacts.tar.gz